package com.weddingwire.export;

import com.itextpdf.html2pdf.HtmlConverter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;

@Service
public class PdfExportService {

    public byte[] exportGuests(List<Map<String, String>> guests) {
        StringBuilder html = buildHtmlTable("Guest List", guests,
                List.of("Name", "Email", "Phone", "Side", "RSVP Status", "Party Size", "Dietary"));
        return convertToPdf(html.toString());
    }

    public byte[] exportChecklist(List<Map<String, String>> items) {
        StringBuilder html = buildHtmlTable("Checklist", items,
                List.of("Title", "Phase", "Due Date", "Completed", "Assigned To"));
        return convertToPdf(html.toString());
    }

    public byte[] exportBudget(List<Map<String, String>> items) {
        StringBuilder html = buildHtmlTable("Budget", items,
                List.of("Category", "Description", "Planned", "Actual", "Notes"));
        return convertToPdf(html.toString());
    }

    public byte[] exportVendors(List<Map<String, String>> vendors) {
        StringBuilder html = buildHtmlTable("Vendors", vendors,
                List.of("Name", "Category", "Rating", "Price Range", "Status", "Contact"));
        return convertToPdf(html.toString());
    }

    public byte[] exportCrew(List<Map<String, String>> crew) {
        StringBuilder html = buildHtmlTable("Wedding Crew", crew,
                List.of("Name", "Role", "Email", "Phone", "External"));
        return convertToPdf(html.toString());
    }

    public byte[] exportTimeline(List<Map<String, String>> items) {
        StringBuilder html = buildHtmlTable("Timeline", items,
                List.of("Time", "End Time", "Title", "Description", "Assigned To"));
        return convertToPdf(html.toString());
    }

    private StringBuilder buildHtmlTable(String title, List<Map<String, String>> data, List<String> headers) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html><html><head><meta charset='UTF-8'>");
        html.append("<style>");
        html.append("body { font-family: Arial, sans-serif; margin: 20px; }");
        html.append("h1 { color: #2C1810; font-size: 24px; }");
        html.append("table { border-collapse: collapse; width: 100%; margin-top: 20px; }");
        html.append("th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }");
        html.append("th { background-color: #2C1810; color: white; }");
        html.append("tr:nth-child(even) { background-color: #f9f5f0; }");
        html.append(".footer { margin-top: 20px; font-size: 10px; color: #888; }");
        html.append("</style></head><body>");
        html.append("<h1>").append(title).append("</h1>");
        html.append("<table><thead><tr>");
        for (String header : headers) {
            html.append("<th>").append(header).append("</th>");
        }
        html.append("</tr></thead><tbody>");
        for (Map<String, String> row : data) {
            html.append("<tr>");
            for (String header : headers) {
                html.append("<td>").append(row.getOrDefault(header, "")).append("</td>");
            }
            html.append("</tr>");
        }
        html.append("</tbody></table>");
        html.append("<div class='footer'>Generated by weddingWire</div>");
        html.append("</body></html>");
        return html;
    }

    private byte[] convertToPdf(String html) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
            HtmlConverter.convertToPdf(html, out);
            return out.toByteArray();
    }
}
